services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    # Environment variables are mostly default in code or .env, but let's keep DB_URL explicit if needed
    environment:
      - DATABASE_URL=file:./prisma/dev.db
    ports:
      - "3000:3000"
    volumes:
      - ./prisma:/app/prisma
    restart: always
